### ISSUE TITLE
name 'gops' is not defined

### ISSUE THREAD

**Issue by zhouzhiqian** [Jingliang-Duan/DSAC-T#1]
Hi, dear authors：

I fail to setup the conda evironment.  When I pip install -e after create the conda environmtne, the output is as follows:

```
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/nubot1/workspace/Distributional-Soft-Actor-Critic-2.0/setup.py", line 27, in <module>
          version=gops.__version__,
      NameError: name 'gops' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```

Any idea for this problem?

Thanks for your help in advance.

**Comment by Jingliang-Duan** [comment]
We sincerely apologize for any inconvenience caused. We are delighted to inform you that we have made the necessary updates to the relevant code, resulting in the successful resolution of the installation problem.

**Comment by Jingliang-Duan** [comment]
> Hi, dear authors：
> 
> I fail to setup the conda evironment. When I pip install -e after create the conda environmtne, the output is as follows:
> 
> ```
> Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [6 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/home/nubot1/workspace/Distributional-Soft-Actor-Critic-2.0/setup.py", line 27, in <module>
>           version=gops.__version__,
>       NameError: name 'gops' is not defined
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> ```
> 
> Any idea for this problem?
> 
> Thanks for your help in advance.


We sincerely apologize for any inconvenience caused. We are delighted to inform you that we have made the necessary updates to the relevant code, resulting in the successful resolution of the installation problem.

**Comment by Jingliang-Duan** [comment]
> Hi, dear authors：
> 
> I fail to setup the conda evironment. When I pip install -e after create the conda environmtne, the output is as follows:
> 
> ```
> Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [6 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/home/nubot1/workspace/Distributional-Soft-Actor-Critic-2.0/setup.py", line 27, in <module>
>           version=gops.__version__,
>       NameError: name 'gops' is not defined
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> ```
> 
> Any idea for this problem?
> 
> Thanks for your help in advance.

Hi, thank you for your attention. We sincerely apologize for any inconvenience caused. We are delighted to inform you that we have made the necessary updates to the relevant code, resulting in the successful resolution of the installation problem.

**Comment by Jingliang-Duan** [comment]
> Hi, dear authors：
> 
> I fail to setup the conda evironment. When I pip install -e after create the conda environmtne, the output is as follows:
> 
> ```
> Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [6 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/home/nubot1/workspace/Distributional-Soft-Actor-Critic-2.0/setup.py", line 27, in <module>
>           version=gops.__version__,
>       NameError: name 'gops' is not defined
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> ```
> 
> Any idea for this problem?
> 
> Thanks for your help in advance.

Apologies for the delay in responding earlier. We've made significant updates to the project, addressing the issue you encountered. Now, after re-downloading the project, you should be able to use it efficiently and without any problems. Please give it a try, and if you need any further assistance, feel free to reach out.

Thank you for your understanding!
