### ISSUE TITLE
No module named 'gops'

### ISSUE THREAD

**Issue by yan320** [Jingliang-Duan/DSAC-T#3]
Hi, when running the training program, it suggests that the module 'gops' is not available, how can I solve this?

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from training.evaluator import create_evaluator
  File "/home/h3c/Distributional-Soft-Actor-Critic-2.0/training/evaluator.py", line 6, in <module>
    from dsac import ApproxContainer
  File "/home/h3c/Distributional-Soft-Actor-Critic-2.0/dsac.py", line 11, in <module>
    from gops.algorithm.base import AlgorithmBase, ApprBase
ModuleNotFoundError: No module named 'gops'

**Comment by drsssssss** [comment]
We had a small problem with our previous work, now we have updated the "dsac.py" file, please re-download the file to solve the problem.

**Comment by yan320** [comment]
Thanks to your immediate reply, a retry solved the above problem.

Best regards.

--------------原始邮件--------------
发件人："Liming&nbsp;Xiao ***@***.***&gt;;
发送时间：2023年9月16日(星期六) 下午5:00
收件人："Jingliang-Duan/Distributional-Soft-Actor-Critic-2.0" ***@***.***&gt;;
抄送："殷焱 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [Jingliang-Duan/Distributional-Soft-Actor-Critic-2.0] No module named 'gops' (Issue #3)
-----------------------------------

 

 
We had a small problem with our previous work, now we have updated the "dsac.py" file, please re-download the file to solve the problem.
