### ISSUE TITLE
Is there an example about using CNN network as policy network and value network?

### ISSUE THREAD

**Issue by TUTUchen0306** [Jingliang-Duan/DSAC-T#6]
I'm trying to use DSAC-T on racecar environment which used image as input.
However, I met some problem when I tried to change the function type to CNN.
It seems like it lacks some arguments, such as "value_conv_type", and does not have cnn file inside networks directory.
Moreover, when I change to used cnn_shared, it lacks arguments like "feature_net".
Therefore, could you provide an example about using the CNN network as policy function and value function?

**Comment by drsssssss** [comment]
Hi, thank you for your inquiry, and we appreciate your interest in our project. Your question is valuable to us. Our DSAC-T algorithm has been integrated into GOPS, a user-friendly PyTorch reinforcement learning solver package. You can explore this solver, which includes various other algorithms such as SAC, TD3, PPO, and more, in the following GitHub repository: [https://github.com/Intelligent-Driving-Laboratory/GOPS](https://github.com/Intelligent-Driving-Laboratory/GOPS)

Regarding your query about using a CNN network as the policy function and value function, we have provided an example in the example_train/dsact directory under the dev branch of the GOPS project. This example demonstrates the usage of a CNN network in a car racing training environment. You can find relevant sample code and documentation in that directory to help you configure and use a CNN network as both the policy and value functions.

If you need further assistance or have any other questions, please feel free to ask. We are here to provide you with full support. Thank you for your interest and support!

**Comment by TUTUchen0306** [comment]
Thanks for your reply!
I met some problem when I tried to used the DSAC-T in GOPS on a new environment.
I wonder if there is any information about adding a new environment to GOPS as I did not find any description about this on the Training Configuration page in the document.

**Comment by drsssssss** [comment]
For adding a new environment to GOPS, please check the  GOPS Documentation (https://gops.readthedocs.io/en/latest/). If you need more detailed guidance, feel free to contact me on WeChat (ID: tip911), or any other contact method that works for you.
