### ISSUE TITLE
训练halfcheetah效果巨差

### ISSUE THREAD

**Issue by xiezhipeng-git** [Jingliang-Duan/DSAC-T#7]
训练halfcheetah效果巨差
在main里使用
parser.add_argument("--env_id", type=str, default="gym_halfcheetah", help="id of environment")
parser.add_argument("--max_iteration", type=int, default=1000000)
其他保持不变。训练完成以后只有几百分。和你们说的1.7W分差距也太大了。而且训练时间巨长。要20多个小时。几乎是我遇上的实现运行效率最慢的强化学习代码了。为什么不使用envpool？使用envpool ppo算法训练，通常cartpole只用几秒钟。
是版本代码有bug?
使用的是https://github.com/Jingliang-Duan/DSAC-T/commit/4707a52fdeafc3663e726cb6c66d5bb43aa5eda4
这个分支修改前，且没有加bias的版本。9293c9a4f6870e659ad8a0d98c39614c6b8897c1 [9293c9a]
希望先得到解释然后我在尝试新版本。

**Comment by Jingliang-Duan** [comment]
谢谢您的使用，有任何问题可以随时和我们沟通，我们的算法也集成在了GOPS RL求解库中， https://gops.readthedocs.io/en/latest/，可以更方便的实现各算法间的性能比较。
